app: chatbot-ui
env: production
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.61.0
values:
  containerPort: 80
  gitRepository: laszlocph/chatbot-ui
  gitSha: '{{ .SHA }}'
  image:
    repository: nginx
    tag: 1.19.3
  replicas: 1
  resources:
    ignoreLimits: true
